<script setup lang="ts">
defineProps<{ samples: any[]; loading: boolean; error: string; showNumber: (value: any, unit?: string) => string; summaryText: (sample: any) => string }>()
const searchQuery = defineModel<string>('searchQuery', { default: '' })
const filterStatus = defineModel<string>('filterStatus', { default: 'Todos' })
const emit = defineEmits(['export', 'open-sample', 'delete-sample', 'retry'])
</script>

<template>
  <UCard class="shadow-sm"><template #header><div class="flex flex-col gap-4 md:flex-row md:items-center md:justify-between"><h3 class="font-bold text-slate-800">Registros históricos</h3><div class="flex flex-wrap gap-3"><UInput v-model="searchQuery" aria-label="Buscar muestra por ID" icon="i-heroicons-magnifying-glass" placeholder="Buscar ID…" color="success" /><USelect v-model="filterStatus" aria-label="Filtrar resultados" :items="['Todos', 'Con usos aptos', 'Con incumplimientos', 'Con ensayos pendientes', 'Históricos']" color="success" /><UButton color="success" variant="outline" icon="i-heroicons-document-arrow-down" @click="emit('export')">Excel</UButton></div></div></template><div v-if="error" role="alert" class="flex flex-wrap items-center gap-3 p-6 text-sm text-rose-700"><span>{{ error }}</span><UButton variant="outline" color="error" @click="emit('retry')">Reintentar</UButton></div><p v-if="loading && !samples.length" role="status" class="p-6 text-sm text-slate-600">Cargando muestras…</p><div v-if="!samples.length && !loading && !error" class="p-8 text-center"><p class="text-slate-500">{{ searchQuery || filterStatus !== 'Todos' ? 'Ninguna muestra coincide con la búsqueda o el filtro.' : 'Aún no hay muestras registradas.' }}</p><UButton v-if="searchQuery || filterStatus !== 'Todos'" class="mt-3" variant="outline" @click="searchQuery = ''; filterStatus = 'Todos'">Limpiar filtros</UButton></div><AppTable v-if="samples.length" label="Registros históricos"><template #head><tr><th class="px-4 py-3">Muestra</th><th class="px-4 py-3">CaCO₃</th><th class="px-4 py-3">CaO</th><th class="px-4 py-3">Resultados</th><th class="px-4 py-3">Fecha</th><th class="px-4 py-3"><span class="sr-only">Acciones</span></th></tr></template><tr v-for="sample in samples" :key="sample.id_muestra" class="hover:bg-slate-50"><td class="px-4 py-3 font-semibold"><button class="rounded text-left text-emerald-700 underline-offset-2 hover:underline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-emerald-600" @click="emit('open-sample', sample)">{{ sample.id_muestra }}<span class="sr-only">: ver detalle</span></button></td><td class="px-4 py-3">{{ showNumber(sample.caco3, '%') }}</td><td class="px-4 py-3">{{ showNumber(sample.cao, '%') }}</td><td class="px-4 py-3">{{ summaryText(sample) }}</td><td class="px-4 py-3">{{ sample.fecha_registro }}</td><td class="px-4 py-3 text-right"><UButton color="error" variant="ghost" icon="i-heroicons-trash" :aria-label="`Eliminar muestra ${sample.id_muestra}`" @click="emit('delete-sample', sample.id_muestra)" /></td></tr></AppTable></UCard>
</template>
