<script setup lang="ts">
defineProps<{ samples: any[]; showNumber: (value: any, unit?: string) => string; summaryText: (sample: any) => string }>()
const searchQuery = defineModel<string>('searchQuery', { default: '' })
const filterStatus = defineModel<string>('filterStatus', { default: 'Todos' })
const emit = defineEmits(['export', 'open-sample', 'delete-sample'])
</script>

<template>
  <UCard class="shadow-sm"><template #header><div class="flex flex-col gap-4 md:flex-row md:items-center md:justify-between"><h3 class="font-bold text-slate-800">Registros históricos</h3><div class="flex flex-wrap gap-3"><UInput v-model="searchQuery" icon="i-heroicons-magnifying-glass" placeholder="Buscar ID..." color="success" /><USelect v-model="filterStatus" :items="['Todos', 'Con usos aptos', 'Con incumplimientos', 'Con ensayos pendientes', 'Históricos']" color="success" /><UButton color="success" variant="outline" icon="i-heroicons-document-arrow-down" @click="emit('export')">Excel</UButton></div></div></template><p v-if="!samples.length" class="p-8 text-center text-slate-400">No se encontraron muestras registradas.</p><AppTable v-else label="Registros históricos"><template #head><tr><th class="px-4 py-3">Muestra</th><th class="px-4 py-3">CaCO₃</th><th class="px-4 py-3">CaO</th><th class="px-4 py-3">Resultados</th><th class="px-4 py-3">Fecha</th><th class="px-4 py-3"></th></tr></template><tr v-for="sample in samples" :key="sample.id_muestra" class="cursor-pointer hover:bg-slate-50" @click="emit('open-sample', sample)"><td class="px-4 py-3 font-semibold">{{ sample.id_muestra }}</td><td class="px-4 py-3">{{ showNumber(sample.caco3, '%') }}</td><td class="px-4 py-3">{{ showNumber(sample.cao, '%') }}</td><td class="px-4 py-3">{{ summaryText(sample) }}</td><td class="px-4 py-3">{{ sample.fecha_registro }}</td><td class="px-4 py-3 text-right" @click.stop><UButton color="error" variant="ghost" icon="i-heroicons-trash" aria-label="Eliminar muestra" @click="emit('delete-sample', sample.id_muestra)" /></td></tr></AppTable></UCard>
</template>
